### ISSUE TITLE
Untertitel von Reihen werden nicht angezeigt

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPropylaeum#1]
@kadowa 
Ich schreibe es mal hierhin, betrifft aber natürlich alle Verlage: Bei der Kurztitelliste der Reihen wird nur der jeweilige Hauptitel angezeigt, nicht aber der Untertitel. Könntest du den auch noch aus der Datenbank ziehen? Und natürlich auch bei der Übersichtsseite der einzelnen Bände.

Viele Grüße
Daniela

**Comment by withanage** [comment]
@wwwubhd das sind etwas gründsätzliche änderungen. ist es auch dringend ?

**Comment by kadowa** [comment]
- [x] Kurztitelliste: https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/commit/d0edb5d8c097849c6cb7304fb8bae3d5fb87a1be, https://github.com/UB-Heidelberg/UBHD-OMPArthistorikum/commit/df557a8ad58b563c378f1d1b65e386a885231b1b, https://github.com/UB-Heidelberg/UBHD_OMPXAsia/commit/4b2e1bb2cbf563b89bde5ecbc8ba034a8b422007, https://github.com/UB-Heidelberg/UBHD-OMPHeibooks/commit/960e6d55adfa2a276c54dd0ee4a25199808b751a.
- [x] Bände-Übersichtsseite: https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/commit/b63e46110b4d9e56e5eec2a56b7591ca4c05ec0d, https://github.com/UB-Heidelberg/UBHD-OMPHeibooks/commit/e75a2a4428af7e0bf5441ae48352d2882214ace2, https://github.com/UB-Heidelberg/UBHD_OMPXAsia/commit/6367376e80cb3760a1ffe27947777a86cf6bea39, https://github.com/UB-Heidelberg/UBHD-OMPArthistorikum/commit/a4d9de1ad798f99b2cb41340797d3a11809153b3

**Comment by kadowa** [comment]
@wwwubhd, eventuell muss noch jemand das Layout in [catalog/series.html#L14](https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/blob/master/views/catalog/series.html#L14) und [series/index.html#L32](https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/blob/master/views/series/index.html#L32) an Marias Vorstellungen anpassen. :innocent:

**Comment by ankosi** [comment]
Neben dem Untertitel soll auch die Bandnummer auftauchen (das gilt auch wieder für alle Imprints, nicht nur für Propylaeum):

http://heiup.uni-heidelberg.de/UBHD_OMPPropylaeum/catalog/series/archber

**Comment by kadowa** [comment]
Ich habe ein neues Issue für die Bandnummer angelegt, da das ein separates Thema ist (gleiche Gefahr wie bei den E-Mail-Threads :wink:).
