### ISSUE TITLE
Erscheinungsjahr und Reihe im Katalog anzeigen

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPPropylaeum#12]
@kadowa, @wwwubhd 

In der Katalogansicht

http://books.ub.uni-heidelberg.de/heibooks/catalog/

zwischen Titel und Abstract einfügen:

**Titel**

Erscheinungsjahr
_Reihe und Band_

Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract

Das Erscheinungsjahr in der gleichen Größe wie die Reihe, aber nicht kursiv.
Reihe und Band so zeigen, wie es bei den Reiheninformationen gezeigt wird.

**Comment by kadowa** [comment]
Erscheinungsjahr Print oder Online?

**Comment by kadowa** [comment]
Eigentlich ist das eine Spezifikation zu https://github.com/UB-Heidelberg/UBHD-OMPHeibooks/issues/7, oder? Damit beschäftigt sich ab morgen @isgrim.

**Comment by ankosi** [comment]
Erscheinungsjahr der Printausgabe.

Die Spezifikation betrifft alle Imprints. Da dies bei der Frage nach der Zitierweise ähnlich war, habe ich es auch an dieser Stelle abgelegt. Könnten wir einen Ort in gitHUB einrichten, wo Issues, die alle Imprints betreffen, angelegt werden können?

**Comment by kadowa** [comment]
Wenn es keine Printausgabe gibt, soll dann kein Erscheinungsjahr angezeigt werden? Insbesondere, wenn es alle Imprints betrifft wird das ja häufig der Fall sein, z.B. bei heiUP.

**Comment by ghost** [comment]
Doch, dann das Erscheinungsjahr des Onlinegangs, würde ich sagen.

Am 15.03.2016 um 13:30 schrieb Katharina Wäschle:

> Wenn es keine Printausgabe gibt, soll dann kein Erscheinungsjahr 
> angezeigt werden? Insbesondere, wenn es alle Imprints betrifft wird 
> das ja häufig der Fall sein, z.B. bei heiUP.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/issues/12#issuecomment-196798315

## 

Dr. Maria Effinger
Leiterin der Abteilung "Historische Sammlungen"
Leiterin der Abteilung "Publikationsdienste"
Heidelberg University Publishing
Zentrales Projektmanagement
Fachreferentin für Kunstgeschichte

Universitätsbibliothek Heidelberg
Plöck 107-109, 69117 Heidelberg
Tel.: +49 (0)6221-543561
http://www.arthistoricum.net
http://www.propylaeum.de
http://hd-historische-bestaende-digital.uni-hd.de
Wunschbuch Kunst http://www.ub.uni-heidelberg.de/fachinfo/kunst/wunschbuch.html

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#8
