### ISSUE TITLE
Punkt hinter "Empfohlene Zitierweise" in HeiBooks entfernen und "DOI: " vor dem DOI ergänzen

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPropylaeum#13]
Abschnitt "Empfohlene Zitierweise" links unter dem Coverbild.
- Generell bitte keinen Punkt hinter den DOI platzieren, es besteht die Gefahr, dass dieser zum DOI gezählt wird und die Weiterlinkung nicht funktioniert.
- Vor dem DOI bitte "DOI: " angeben.

Beispielseite:

http://books.ub.uni-heidelberg.de/heibooks/catalog/book/11

**Comment by kadowa** [comment]
Die Angabe mit Punkt wurde hier explizit spezifiziert: https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/10#issuecomment-197281385

Der Code für die Generierung der Zitierweise wird demnächst von @isgrim überarbeitet. Bis dahin sollte daher auch die Anforderung noch mal vereinheitlicht werden. Die bisherige Anforderung(sentwicklung) ist hier nachvollziehbar, https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/10, daher würde ich dieses Issue gerne schließen.

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#32
