### ISSUE TITLE
Download-Buttons

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPropylaeum#2]
![download1](https://cloud.githubusercontent.com/assets/8066366/12916443/d68edda6-cf32-11e5-9967-2375fc4495a4.png)
![download2](https://cloud.githubusercontent.com/assets/8066366/12916447/d7feeed8-cf32-11e5-86ee-664cae2ebd8a.png)

Ursache ist vermutliche, dass mehrere Dateien, die als komplettes Buch (über genre_id) gekennzeichnet sind, vorliegen. Umgekehrt wird kein Downloadbutton angezeigt, wenn das Buch nur in einzelnen Kapiteln herunterladbar ist.

**Comment by withanage** [comment]
es gibt dazu ein fix in arthistoricum. muss  ins propylaeum integriert werden. Ich kümmere mich drum wenn ich zurück bin.

**Comment by kadowa** [comment]
@withanage, wie funktioniert dein Fix? IMHO wäre es sinnvoll, einfach bei der Eingabe in OMP nur eine Datei als "Book manuscript" zu kennzeichnen, statt, wie es hier offenbar passiert ist zwei oder vier.

**Comment by withanage** [comment]
@kadowa  : Das fix war praktisch auch mit  genre-id. 
In diesem Fall ist es wirklich das 4 mail das Buch hochgeladen.
@ankosi oder @wwwubhd  (Daniela) wisst Ihr vielleicht warum wurde  dieses Monograph so hochgeladen ?
[https://books.ub.uni-heidelberg.de/index.php/propylaeum/workflow/production/37](url)
Anhang 
![screenshot from 2016-03-11 13 36 55](https://cloud.githubusercontent.com/assets/1921992/13702352/576e48a8-e78e-11e5-9eed-88a32678f506.png)

**Comment by kadowa** [comment]
@withanage, Frau Bemmann betreut Propylaeum. Ich habe schon im OMP-Anwendertreffen alle informiert, dass nur ein Full-PDF pro Submission eingetragen werden darf und soweit ich den Überblick habe, sind die meisten korrigiert.

**Comment by ankosi** [comment]
Katrin Bemmann sagte, dass hier verschiedene Teile (Buch + 3 
Farbtafel-Anhänge) hochgeladen wurden.

Am 11.03.2016 um 13:37 schrieb Dulip Withanage:

> @kadowa https://github.com/kadowa : Das fix war praktisch auch mit 
> genre-id.
> In diesem Fall ist es wirklich das 4 mail das Buch hochgeladen.
> screenshot from 2016-03-11 13 36 55 
> https://cloud.githubusercontent.com/assets/1921992/13702352/576e48a8-e78e-11e5-9eed-88a32678f506.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/issues/2#issuecomment-195349981.

##

**Comment by withanage** [comment]
@ankosi
Wir haben bisher das Konzept das ganze Buch und Kapiteln.
In dem Fall sind alle 4 PDFs als Monograph markiert.  Daher ist es nicht möglich das ganze  Buch zu identifizieren.
Daher gibt es eine Möglichkeit den Typ von dem Anhänge zu ändern.
Ist die Frage, sollten sie alle trotzdem ausgegeben werden ?

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#13
