### ISSUE TITLE
Bilder der Reihen werden nicht angezeigt

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPropylaeum#3]
@kadowa 
Auf der Reihenübersichtsseite soll eigentlich links davon jeweils das Bild aus OMP gezogen werden (so wie es bei heiUP-arthistoriocum auch geht), allerdings funktioniert das nicht.

**Comment by withanage** [comment]
@wwwubhd  falls es nicht zu dringend  ist, kümmere ich mich darum.

**Comment by kadowa** [comment]
@withanage, ich habe einen Link auf das entsprechende OMP-Verzeichnis gesetzt.
