### ISSUE TITLE
Autoren/Herausgeber bei Sammelbänden

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPropylaeum#4]
@kadowa 
Bei Sammelbänden sollen nur die Herausgeber, nicht aber die Autoren angezeigt werden.

**Comment by withanage** [comment]
@wwwubhd  falls nicht zu dringend ist, mache ich das.

**Comment by kadowa** [comment]
@wwwubhd, sollen Herausgeber in der Anzeige noch speziell gekennzeichnet werden, also z.B.

```
Editor A, Editor B (Hrsg.)
Titel
```

?

**Comment by ghost** [comment]
@kadowa @withanage 
Ja, bitte die Angabe hinzu fügen

**Comment by kadowa** [comment]
@ankosi, @wwwubhd könnt ihr bei Gelegenheit überprüfen, ob alles wie gewünscht angezeigt wird, bevor ich die Änderung in alle Portale übernehme?

**Comment by ghost** [comment]
Liebe Katharina,

danke!
http://heiup.uni-heidelberg.de/UBHD_OMPPropylaeum/catalog/series/archber
sieht für mich sehr gut aus!
Nur bei Band 2 hat es den Autor verschluckt, aber der ist vielleicht 
nicht richtig eingegeben?
Viele Grüße, MAria

Am 08.03.2016 um 17:16 schrieb Katharina Wäschle:

> @AnjaKonopka https://github.com/AnjaKonopka, @wwwubhd 
> https://github.com/wwwubhd könnt ihr bei Gelegenheit überprüfen, ob 
> alles wie gewünscht angezeigt wird, bevor ich die Änderung in alle 
> Portale übernehme?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/issues/4#issuecomment-193844710.

## 

Dr. Maria Effinger
Leiterin der Abteilung "Historische Sammlungen"
Leiterin der Abteilung "Publikationsdienste"
Heidelberg University Publishing
Zentrales Projektmanagement
Fachreferentin für Kunstgeschichte

Universitätsbibliothek Heidelberg
Plöck 107-109, 69117 Heidelberg
Tel.: +49 (0)6221-543561
http://www.arthistoricum.net
http://www.propylaeum.de
http://hd-historische-bestaende-digital.uni-hd.de
Wunschbuch Kunst http://www.ub.uni-heidelberg.de/fachinfo/kunst/wunschbuch.html

**Comment by ankosi** [comment]
Sieht prima aus! Danke, Katharina. Eine Sache wäre noch zu überlegen:

Liebe Maria, wollen wir - wenn es mehrere Herausgeber sind - dies an der
Abkürzung deutlich machen: Hrsgg.??

Liebe Grüße
Anja

----- Nachricht von Katharina Wäschle notifications@github.com ---------
     Datum: Tue, 08 Mar 2016 08:16:57 -0800
       Von: Katharina Wäschle notifications@github.com
Antwort an: UB-Heidelberg/UBHD-OMPPropylaeum
reply@reply.github.com
   Betreff: Re: [UBHD-OMPPropylaeum] Autoren/Herausgeber bei
Sammelbänden (#4)
        An: UB-Heidelberg/UBHD-OMPPropylaeum
UBHD-OMPPropylaeum@noreply.github.com
        Cc: AnjaKonopka konopka@ub.uni-heidelberg.de

> @AnjaKonopka[1], @wwwubhd[2] könnt ihr bei Gelegenheit überprüfen, ob
> alles wie gewünscht angezeigt wird, bevor ich die Änderung in alle
> Portale übernehme?
> 
>   —
> Reply to this email directly or view it on GitHub[3].
>       

## ----- Ende der Nachricht von Katharina Wäschle notifications@github.com

## Links:

[1] https://github.com/AnjaKonopka
[2] https://github.com/wwwubhd
[3]  
https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/issues/4#issuecomment-193844710
  Anja Konopka
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109, 69117 Heidelberg
Tel: +49 6221 542569
E-Mail: konopka@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de/

**Comment by ankosi** [comment]
@kadowa, Wenn mehr als drei Herausgeber oder Autoren angegeben sind, sollen die ersten drei aufgeführt werden, nach dem dritten soll  "et al." stehen:

Bei mehr als drei Autoren also:
Vorname Nachname, Vorname Nachname, Vorname Nachname et al.

Bei mehr als drei Herausgebern:
Vorname Nachname, Vorname Nachname, Vorname Nachname et al. (Hrsg)

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#15
