### ISSUE TITLE
Katalogreihenfolge nach Erscheinungsjahr

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPropylaeum#5]
@kadowa @withanage 
Hier ein weiterer Wunsch: In der Katalogübersicht von Propylaeum (vermutlich aber auch nach und nach für die anderen Presses) soll die Sortierung nach Erscheinungsjahr möglich sein.

Viele Grüße
Daniela

**Comment by kadowa** [comment]
Für arthistoricum ist das jetzt umgesetzt: http://heiup.uni-heidelberg.de/UBHD_OMParthistoricum/catalog Es sollte aber noch jemand, der sich mit den Inhalten auskennt, überprüfen, ob die Reihenfolge so stimmt.

**Comment by kadowa** [comment]
Ist jetzt für alle Portale umgesetzt. @wwwubhd , @AnjaKonopka, könnt ihr überprüfen (bzw. die Anfrage weiterleiten), ob die Reihenfolge so wie gewünscht erscheint und dann ggf. das Häkchen setzen?
- [ ] Arthistoricum (http://heiup.uni-heidelberg.de/arthistoricum/catalog)
- [ ] Propylaeum (http://heiup.uni-heidelberg.de/propylaeum/catalog)
- [ ] heiBOOKS (http://heiup.uni-heidelberg.de/heibooks/catalog)
- [ ] heiUP (http://heiup.uni-heidelberg.de/heiup/catalog)
- [ ] XAsia (http://heiup.uni-heidelberg.de/UBHD_OMPXAsia/catalog)

**Comment by dastewo** [comment]
@kadowa 
@withanage 
Könntet ihr (erst einmal nur für Propylaeum) die Sortierung der Reihen (also nicht des Katalogs) alphabetisch umsetzen?

Viele Grüße
Daniela

**Comment by kadowa** [comment]
@danielawolf, wenn es nicht den Katalog betrifft, bitte in ein eigenes Issue auslagern! Sonst haben wir wieder das Problem, dass Anforderungen verloren gehen. :wink:

**Comment by dastewo** [comment]
@kadowa Das halte ich nur für dann sinnvoll, wenn die Mechanik dahinter eine andere ist. Das wiederum kann ich aber nicht beurteilen.

**Comment by kadowa** [comment]
Ist eine andere Seite (=Funktion) und ein anderes Sortierungskriterium, daher bitte separat. Gibt es eigentlich schon Feedback zu den einzelnen Portalen? Würde dieses Issue langsam gerne mal schließen.

**Comment by dastewo** [comment]
Ich habe nichts gehört.

**Comment by kadowa** [comment]
:sob:

**Comment by ghost** [comment]
Das war meine Rückmeldung dazu (Mail 2.3.) - da sollte aber erst noch 
Dulip befragt werden :-)
Liebe Grüße, Maria

---

Am liebsten wäre mir, wir würden es für alle 5 gleich machen
Vorschlag
Absteigend chronologisch nach Erscheinungsjahr des Buches
Bei Retrobänden: Erscheinungsjahr der Printvorlage
Bei genuinen Bände: Identisch mit Onlinestellung
Das hätte zur Folge, dass wir immer den neuesten Band oben hätten (und 
nehmen in Kauf, dass Retrobände mit älteren Erscheinungsjahren sich dann 
weiter unten einsortieren.)

Mir scheint diese für die Nutzer die beste und am einfachsten 
nachvollziehbare Lösung zu sein.

[Später wird ja noch die Möglichkeit hinzukommen, auf dieser Seite auch 
zu suchen bzw, auch umzusortieren]

Am 11.03.2016 um 13:24 schrieb Katharina Wäschle:

> Ist eine andere Seite (=Funktion) und ein anderes 
> Sortierungskriterium, daher bitte separat. Gibt es eigentlich schon 
> Feedback zu den einzelnen Portalen? Würde dieses Issue langsam gerne 
> mal schließen.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/issues/5#issuecomment-195347476.

## 

Dr. Maria Effinger
Leiterin der Abteilung "Historische Sammlungen"
Leiterin der Abteilung "Publikationsdienste"
Heidelberg University Publishing
Zentrales Projektmanagement
Fachreferentin für Kunstgeschichte

Universitätsbibliothek Heidelberg
Plöck 107-109, 69117 Heidelberg
Tel.: +49 (0)6221-543561
http://www.arthistoricum.net
http://www.propylaeum.de
http://hd-historische-bestaende-digital.uni-hd.de
Wunschbuch Kunst http://www.ub.uni-heidelberg.de/fachinfo/kunst/wunschbuch.html

**Comment by withanage** [comment]
@kadowa  @wwwubhd 
hier brauchen wir die  Sortier-funktion  nach   Typ
z.B. ?sortby= Erscheinungsjahr&order=absteigend  
Sollte per  URL Argument sortierbar sein.
Diese Funktion sollte bei allen Portalen verwendet werden können.
Eine Vorieinstellung können wir für jedes Portal seperat konfigirieren, in confing Datei.

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#14
