### ISSUE TITLE
Zitierweise

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPropylaeum#7]
Die empfohlene Zitierweise in nicht korrekt. Erwünscht ist

```
Nachname, Vorname, Titel. Ort: Verlag, Jahr.
```

Besonderheiten ergeben sich bei Sammelbänden:

```
Young, Glenn, ed. The Best American Short Plays, 2002–2003. New York: Applause, 2007.
```

oder

```
Bonnefoy, Yves. New and Selected Poems. Edited by John Naughton and Anthony Rudolf. Chicago: University of Chicago Press, 1995.
```

@ankosi, habe ich das so korrekt übertragen? Gibt es schon eine Entscheidung für einen der beiden Zitierstile bei Sammelbänden?

**Comment by kadowa** [comment]
@ankosi, wie verbinde ich denn mehrere Autoren oder Herausgeber? Mit Komma? 'Und'/'And'?

Mit Komma wirkt es etwas unübersichtlich, finde ich.

**Comment by ankosi** [comment]
@kadowa 

nach CMOS ist vorgesehen, bei bis zu zwei Autoren bzw. Herausgebern ein
"und" zu setzen, bei mehr als zweien die ersten beiden durch Komma
voneinander zu trennen und den letzten mit und anzufügen.

     

> @akosi1], wie verbinde ich denn mehrere Autoren oder Herausgeber?
> Mit Komma? 'Und'/'And'?
> 
>   Mit Komma wirkt es etwas unübersichtlich, finde ich.
> 
>   —
> Reply to this email directly or view it on GitHub[2].
>       

## ----- Ende der Nachricht von Katharina Wäschle notifications@github.com

## Links:

[1] https://github.com/AnjaKonopka
[2]  
https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/issues/7#issuecomment-188839360

**Comment by kadowa** [comment]
Ok, danke. Einfach geht aber anders. :smile:

**Comment by ankosi** [comment]
**AKTUALISIERT AM 11.03.2016**

Für die Online-Version sollte so zitiert werden:
Monographie: 
Autorname, Vorname. _Titel: Untertitel_.Verlagsort: Verlag,  Jahr. doi:xx.

Sammelband: 
Name, Vorname, Hrsg. _Titel: Untertitel._ Verlagsort: Verlag, Jahr. doi.

Werk mit zwei Autoren:
Autorname, Vorname und Vorname Nachname. _Titel: Untertitel._ Ort: Verlag, Jahr. doi.

Werk mit mehr als zwei Autoren:
Autorname, Vorname, Vorname Nachname und Vorname Nachname. _Titel: Untertitel._ Ort: Verlag, Jahr. doi.

Werk, das in einer Reihe erscheint:
Autorname, Vorname. _Titel: Untertitel_. Reihe, Bd. Verlagsort: Verlag,  Jahr. doi:xx.

Bei den Online-Publikationen geben wir als Verlag grundsätzlich "unsere" Verlage an, bei Print den Verlag, in dem das Werk tatsächlich als Buch erscheint/erschienen ist.

**Comment by ankosi** [comment]
@kadowa Da dieser Zitierissue natürlich nicht nur Propylaeum, sondern auch alle anderen "Verlage" betrifft: Könntest Du ein allgemeineres Portal umziehen?

**Comment by ankosi** [comment]
@kadowa, Ich habe mit Maria geklärt, wie wir Erscheinungsdatum und ISBN darstellen, wenn wir
1. Print und PDF
2. Print (nicht mehr lieferbar) und PDF
3. Print (nicht mehr lieferbar), Print (lieferbar durch uns) und PDF haben.

Das Ergebnis ist:
1. Wenn Buch und Online-PDF beim gleichen Verlag (also bei uns) erscheinen und das Erscheinungsjahr das gleiche ist, lassen wir es so, wie es als "Normalfall" bisher geplant ist:

> Empfohlene Zitierweise
> 
> Vorname, Nachname: Titel. Ort: Verlag, Jahr. doi ....

 Bei den ISBNs nennen wir hingegen beide, PDF und Print, an der Stelle, an der bisher schon die PDF-ISBN steht, in der Form:

```
ISBN: xxx (PDF) [vom Reiter PDF]
ISBN: xxxx (Buch ) [-> vom Reiter Softcover/Hardcover]
```
1. Wenn Buch Online-PDF ursprünglich in einem anderen Verlag erschienen ist,  beziehen wir uns bei der empfohlenen Zitierweise auf das PDF. Unterhalb von "Veröffentlicht am 23.07.2015" schreiben wir dann:
   
   Originalveröffentlichung bei ... [= Verlagsname] im Jahr ... [Erscheinungsjahr].
   
   Bei den ISBNs nennen wir ebenfalls beide, und zwar so:
   
     ISBN: 9783946054016 (PDF)
     ISBN: xxxx (Orig.-Ausg.)
2. Wenn wir Buch: vergriffen (Originalveröffentlichung) und Print on Demand (über uns) sowie das PDF haben und sich Print-on-Demand und PDF-Erscheinungsjahr unterscheiden, wird es natürlich schwierig. Ich würde dann ebenfalls unter "Veröffentlicht am ..." schreiben:
   Orig.-Ausg. bei ... [= Verlagsname]  ... [Erscheinungsjahr]
   Buchausg. bei ... [z. B. heiBOOKS] ... [Erscheinungsjahr]
   
   Bei den ISBNs nennen wir alle drei:
   
     ISBN: 9783946054016 (PDF)
     ISBN: xxxx (Orig.-Ausg.)
     ISBN: xxxx (Buchausg. heiBOOKS)
- Das Erscheinungsjahr des PDF ziehen wir vom Reiter PDF, dort ist es "Publication date". 
- Das  Erscheinungsjahr der Originalveröffentlichung am besten von einem eigenen Reiter "Originalveröffentlichung", damit wir auch dort die ISBN und den Verlag eingeben können, als Bezug für das Datum wählen wir "Publication date of print counter part"
- Das Erscheinungsjahr der PoD-Veröffentlichung von einem Reiter "Softcover" oder "Hardcover" (je nachdem, was es ist), dort kann die Bezeichnung für das Datum schwanken, da es sich ja auch um eine Neuauflage handeln kann. Auf diesem Reiter sollten wir ebenfalls ISBN und Verlag eingeben.

**Comment by kadowa** [comment]
@ankosi, könntest du https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/issues/7#issuecomment-191317356 in ein eigenes Issue kopieren? Die Publikationsformate sind ein separates Thema.

**Comment by kadowa** [comment]
Wie soll eigentlich die Anzeige in unterschiedlichen Sprachen gehandhabt werden? Ändert sich die Zitierweise, wenn die Seite auf Englisch aufgerufen wird?

Generell wäre es eigentlich auch schön, die Zitation in verschiedenen Formaten zum Herunterladen anzubieten, z.B. in Bibtex. Aber das ist eine etwas aufwändigere Geschichte.

**Comment by ankosi** [comment]
Ich habe die Beispiele für Musterzitationen (Comment vom 29. Februar) 
noch einmal überarbeitet. CMOS ist irgendwie maximal kompliziert :-(

Für die englische Seite sind folgende Anpassungen nötig:

Hrsg.  (einer) -> ed.
Hrsg. (mehrere) -> eds.
und -> and
vor "and" ein Komma.
Bd. -> vol.

Jacobs, Sue-Ellen, Wesley Thomas, and Sabine Lang, eds. /Two-Spirit 
People: Native American Gender Identity, Sexuality, and Spirituality/. 
Urbana: University of Illinois Press, 1997.

Zitation in verschiedenen Formaten zum Herunterladen finde ich natürlich 
eine sehr charmante Sache, aber ich würde es im Moment zurückstellen, da 
es so vieles anderes gibt, was uns unter den Nägeln brennt.

Am 07.03.2016 um 15:39 schrieb kadowa:

**Comment by kadowa** [comment]
Bis auf Reihentitel und Bandnummer ist alles umgesetzt. @ankosi, kannst du alle Publikationen prüfen? Das einzige Problem sind noch die fehlenden Übersetzungen für 'and', 'eds' und 'ed'. Sobald ich diese in die Lokalisierungs-Datei eintrage, fehlen plötzlich sämtliche deutsche Übersetzungen. Da ich das für das größere Übel halte, habe ich die Übersetzungen jetzt erstmal weggelassen. Wenn alles ok ist, können wir die Änderungen Montag hoffentlich ins Produktiv-System umziehen.

**Comment by kadowa** [comment]
Übersetzungen sind da, Reihentitel folgt hoffentlich heute ...

**Comment by kadowa** [comment]
@ankosi, leider muss ich dich schon wieder in die Untiefen von CMS schicken. Wie wird denn im Englischen die Reihe zitiert? "Vol."? "vol."? Und wie gehe ich mit dem Untertitel um?

**Comment by ankosi** [comment]
"vol" klein. Zwischen Titel und Untertitel bitte einen Punkt setzen.

Am 14.03.2016 um 11:36 schrieb kadowa:

**Comment by kadowa** [comment]
Ist umgesetzt: https://github.com/UB-Heidelberg/UBHD-OMPHeibooks/commit/033ece266dc5f8e7e761bb73392be530a481fffd

Damit wäre erstmal alles abgehakt, wenn ich das richtig sehe. @ankosi, kann ich das Issue damit schließen?

**Comment by ankosi** [comment]
@kadowa: Super, das sieht schon sehr gut aus! Die CC-Lizenz wird im Moment
aber noch zwei mal als Link angezeigt und beide Links funktionieren - kann
man einen streichen?

----- Nachricht von Katharina Wäschle notifications@github.com ---------
     Datum: Mon, 14 Mar 2016 06:45:25 -0700
       Von: Katharina Wäschle notifications@github.com
Antwort an: UB-Heidelberg/UBHD-OMPPropylaeum
reply@reply.github.com
   Betreff: Re: [UBHD-OMPPropylaeum] Zitierweise (#7)
        An: UB-Heidelberg/UBHD-OMPPropylaeum
UBHD-OMPPropylaeum@noreply.github.com
        Cc: AnjaKonopka konopka@ub.uni-heidelberg.de

> Ist umgesetzt: UB-Heidelberg/UBHD-OMPHeibooks@033ece2[1]
> 
>   Damit wäre erstmal alles abgehakt, wenn ich das richtig sehe.
> @AnjaKonopka[2], kann ich das Issue damit schließen?
> 
>   —
> Reply to this email directly or view it on GitHub[3].
>       

## ----- Ende der Nachricht von Katharina Wäschle notifications@github.com

## Links:

[1]  
https://github.com/UB-Heidelberg/UBHD-OMPHeibooks/commit/033ece266dc5f8e7e761bb73392be530a481fffd
[2] https://github.com/AnjaKonopka
[3]  
https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/issues/7#issuecomment-196316379
  Anja Konopka
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109, 69117 Heidelberg
Tel: +49 6221 542569
E-Mail: konopka@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de/

**Comment by ankosi** [comment]
@kadowa, Im Moment ist ide Ausgabe von Werken mit mehr als zwei Autoren bzw. Herausgebern so
Autorname, Vorname, **Nachname, Vorname** und Vorname Nachname. Titel: Untertitel. Ort: Verlag, Jahr. doi. 
programmiert.

Gewünscht ist aber: 
Autorname, Vorname, **Vorname Nachname** und Vorname Nachname. Titel: Untertitel. Ort: Verlag, Jahr. doi.

**Comment by ankosi** [comment]
@kadowa 

Ausgegeben werden soll ja:

Wenn es Herausgeber und Autoren gibt: Nur die Herausgeber.
Wenn es mehr als drei Herausgeber gibt. Nur die ersten drei.
Wenn es mehr als drei Autoren gibt: Auch die ersten drei.

Zusätzlicher Wunsch meinerseits: Wenn es mehr als drei Autoren bzw. Herausgeber gibt, bitte "et. al." anfügen. (Bei der empfohlenen Zitierweise und im Haupttext).

**Comment by kadowa** [comment]
"et al." ist jetzt bei der Zitierweise drin. Was genau ist denn mit "im Haupttext" gemeint?

**Comment by ankosi** [comment]
Danke!! Mit "Haupttext" meinte ich die Informationen, die rechts vom 
Bild angezeigt werden.

**Comment by ankosi** [comment]
Leider werden im Moment noch alle Autoren ausgegeben:

http://heiup.uni-heidelberg.de/UBHD_OMPHeibooks/catalog/book/62

Dabei macht es keinen Unterschied, ob ich den Haken bei "Edit in browse 
lists" gesetzt habe oder nicht.

Am 16.03.2016 um 09:17 schrieb kadowa

**Comment by kadowa** [comment]
Ja, in der Überschrift, aber bei der Zitierweise nicht. Da es in diesem Issue um die Zitation geht, hatte ich nur diese Baustelle im Kopf. Das andere betrifft nämlich mindestens noch die Katalog- und Bändeansicht ebenso, oder? Dafür sollten wir #4 wieder öffnen.

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#10

**Comment by withanage** [comment]
@ankosi 
das titcket wurde in 
https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/51
behandelt. 
Daher wurde explizit geschlossen.
