### ISSUE TITLE
Anzeige Bandnummern bei Reihen

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPropylaeum#9]
S. https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/issues/1#issuecomment-190668957

**Comment by kadowa** [comment]
@AnjaKonopka, wo soll die Bandnummer stehen? Als separate Zeile unter dem Titel? Dem Titel vorangestellt? Wie ist die englische Übersetzung für Band?

Damit die Anzeige funktioniert, müssen außerdem noch Datenbankkorrekturen vorgenommen werden; in einigen Fällen steht bei series_position "Band x" hardkodiert, bei anderen nicht. Für die englischsprachige Anzeige ist das ja sicher ungeeignet, oder?

![series_position](https://cloud.githubusercontent.com/assets/8066366/13454170/91f200fe-e055-11e5-9915-2d186e60e98f.png)

**Comment by kadowa** [comment]
Hier mein Layout-Vorschlag für die Integration der Bandnummern (Deutsch und Englisch): http://heiup.uni-heidelberg.de/UBHD_OMPPropylaeum/catalog/series/archber?lang=de

@AnjaKonopka, kannst du das an Maria weiterleiten, damit sie kurz Feedback/ihr ok gibt?

Danach müssten wir dann nur noch die DB korrigieren und das in den Best-Practice-Guide aufnehmen.

**Comment by ankosi** [comment]
@kadowa, Maria ist mit deinem Vorschlag sehr glücklich. Eine Ergänzungsbitte allerdings: Vor dem "Band ..." sollte die Reihe stehen, also z. B. so:
Archäologische Berichte, Band 11

**Comment by kadowa** [comment]
Ist ergänzt: http://heiup.uni-heidelberg.de/propylaeum/catalog/series/archber?lang=en

Allerdings ist dadurch ein neuer Bug ans Licht gekommen: https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/issues/10
